AWSTemplateFormatVersion: "2010-09-09"
Description: Grant existing IAM user 'joboro' permission to create S3 buckets

Resources:
  JoboroS3Policy:
    Type: AWS::IAM::Policy
    Properties:
      PolicyName: AllowS3BucketCreation
      Users:
        - joboro   # existing IAM user
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Action:
              - s3:CreateBucket
              - s3:PutBucketAcl
              - s3:PutBucketPolicy
              - s3:PutBucketPublicAccessBlock
              - s3:PutEncryptionConfiguration
            Resource: "*"