AWSTemplateFormatVersion: '2010-09-09'
Description: Simple EC2 Instance Windows 2019 Server with 2019 access with RDP access

Resources:
  InstanceSecurityGroup:
    Type: 'AWS::EC2::SecurityGroup'
    Properties:
      GroupDescription: Enable RDP access via port 3389
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 3389
          ToPort: 3389
          CidrIp: '0.0.0.0/0'  # Open to the world; restrict as needed
      Tags:
        - Key: Name
          Value: WindowsSG01

  MyKeypair:
    Type: 'AWS::EC2::KeyPair'
    Properties:
      KeyName: GitHubActionsKeyPair01
      Tags:
        - Key: Name
          Value: GitHubActionsKeyPair01

  MyInstance:
    Type: 'AWS::EC2::Instance'
    Properties:
      InstanceType: t3.micro
      ImageId: ami-0d8940f0876d45867  # Windows Server 2019 Base AMI in us-east-1
      SecurityGroupIds:
        - Ref: InstanceSecurityGroup
      KeyName: 
        Ref: MyKeypair